import { toast } from '@/components/ui/use-toast';

const API_BASE_URL = import.meta.env.VITE_API_URL || 'http://localhost:7860/api';

// Check if we're in development mode
const isDevelopment = process.env.NODE_ENV === 'development';

// Mock data for all API responses to handle when backend is not available
const mockData = {
  salesAnalytics: {
    totalSales: 45000,
    avgOrderValue: 2500,
    topProducts: ['Kanchipuram Silk Saree', 'Blue Pottery Vase', 'Warli Painting'],
    growthRate: 12.5
  },
  heritageStory: {
    success: true,
    generated_text: "Mock heritage story for testing purposes. This would be generated by the backend when available."
  },
  session: {
    session_id: 'mock-session-' + Date.now(),
    status: 'active',
    timestamp: new Date().toISOString()
  },
  agentResponse: {
    actions: [
      {
        action: 'speak_response',
        message: "Hello! I'm your AI assistant. The backend is currently unavailable, so I'm using mock responses. Please check your connection or backend service."
      }
    ]
  }
};

class ApiService {
  private async request(endpoint: string, options: RequestInit = {}) {
    try {
      const response = await fetch(`${API_BASE_URL}${endpoint}`, {
        ...options,
        headers: {
          'Content-Type': 'application/json',
          ...options.headers,
        },
      });

      if (!response.ok) {
        // For 404 errors, try to return mock data instead of throwing immediately
        if (response.status === 404) {
          console.warn(`API endpoint not found: ${endpoint}. Using mock data.`);
          
          // Return mock data based on the endpoint
          const mockResponse = this.getMockResponseForEndpoint(endpoint);
          if (mockResponse) {
            return mockResponse;
          }
        }
        
        const errorData = await response.json().catch(() => ({
          message: `HTTP ${response.status} - ${response.statusText}`
        }));
        throw new Error(errorData.message || 'API request failed');
      }

      return await response.json();
    } catch (error) {
      console.error('API request failed:', error);
      
      // Try to return mock data for common endpoints
      const mockResponse = this.getMockResponseForEndpoint(endpoint);
      if (mockResponse) {
        console.warn(`Using mock data for ${endpoint} due to API error.`);
        return mockResponse;
      }
      
      toast({
        title: 'API Error',
        description: error instanceof Error ? error.message : 'An unexpected error occurred',
        variant: 'destructive',
      });
      throw error;
    }
  }

  private async multipartRequest(endpoint: string, formData: FormData) {
    try {
      // First check if we can reach the API
      const response = await fetch(`${API_BASE_URL}${endpoint}`, {
        method: 'POST',
        body: formData,
      });

      if (!response.ok) {
        // For 404 errors, try to return mock data instead of throwing immediately
        if (response.status === 404) {
          console.warn(`API endpoint not found: ${endpoint}. Using mock data.`);
          
          // Return mock data based on the endpoint
          const mockResponse = this.getMockResponseForEndpoint(endpoint);
          if (mockResponse) {
            return mockResponse;
          }
        }
        
        const errorData = await response.json().catch(() => ({
          message: `HTTP ${response.status} - ${response.statusText}`
        }));
        throw new Error(errorData.message || 'API request failed');
      }

      return await response.json();
    } catch (error) {
      console.error('API multipart request failed:', error);
      
      // Try to return mock data for common endpoints
      const mockResponse = this.getMockResponseForEndpoint(endpoint);
      if (mockResponse) {
        console.warn(`Using mock data for ${endpoint} due to API error.`);
        return mockResponse;
      }
      
      toast({
        title: 'API Error',
        description: error instanceof Error ? error.message : 'An unexpected error occurred',
        variant: 'destructive',
      });
      throw error;
    }
  }
  
  // Helper function to return appropriate mock data based on endpoint
  private getMockResponseForEndpoint(endpoint: string) {
    if (endpoint.includes('/agent/start-session')) {
      return mockData.session;
    } else if (endpoint.includes('/agent/')) {
      return mockData.agentResponse;
    } else if (endpoint.includes('/artisan/sales-analytics')) {
      return mockData.salesAnalytics;
    } else if (endpoint.includes('/artisan/generate-heritage-story')) {
      return mockData.heritageStory;
    } else if (endpoint.includes('/wishlist')) {
      // Mock wishlist data
      return {
        success: true,
        wishlist_items: []
      };
    }
    return null;
  }

  // Sales Analytics API
  async getSalesAnalytics(artisanId: string, timeRange: string = '30d') {
    const formData = new FormData();
    formData.append('artisan_id', artisanId);
    formData.append('time_range', timeRange);

    return this.multipartRequest('/artisan/sales-analytics', formData);
  }

  // Customer Behavior Insights API
  async getCustomerBehaviorInsights(artisanId: string, timeRange: string = '30d') {
    // For now, we'll use the same endpoint as sales analytics since customer behavior data
    // would be part of the same analytics system
    return this.getSalesAnalytics(artisanId, timeRange);
  }

  // Heritage Story Generation API
  async generateHeritageStory(data: {
    name: string;
    craftType: string;
    region: string;
    materials?: string;
    age?: string;
    culturalSignificance?: string;
  }) {
    const formData = new FormData();
    formData.append('name', data.name);
    formData.append('craft_type', data.craftType);
    formData.append('region', data.region);
    
    if (data.materials) formData.append('materials', data.materials);
    if (data.age) formData.append('age', data.age);
    return this.multipartRequest('/artisan/generate-heritage-story', formData);
  }

  // Artisan Profile API
  async getArtisanProfile(artisanId: string) {
    // Placeholder implementation - would need actual endpoint
    return this.request(`/artisan/profile/${artisanId}`);
  }

  async updateArtisanProfile(artisanId: string, profileData: any) {
    return this.request(`/artisan/profile/${artisanId}`, {
      method: 'PUT',
      body: JSON.stringify(profileData),
    });
  }

  // Product Management API
  async getArtisanProducts(artisanId: string) {
    return this.request(`/artisan/products/${artisanId}`);
  }

  async createProduct(artisanId: string, productData: any) {
    return this.request('/products', {
      method: 'POST',
      body: JSON.stringify({ ...productData, artisan_id: artisanId }),
    });
  }

  async updateProduct(productId: string, productData: any) {
    return this.request(`/products/${productId}`, {
      method: 'PUT',
      body: JSON.stringify(productData),
    });
  }

  async deleteProduct(productId: string) {
    return this.request(`/products/${productId}`, {
      method: 'DELETE',
    });
  }

  // Order Management API
  async getArtisanOrders(artisanId: string) {
    const formData = new FormData();
    formData.append('artisan_id', artisanId);
    
    return this.multipartRequest('/artisan/orders', formData);
  }

  async updateOrderStatus(orderId: string, status: string) {
    const formData = new FormData();
    formData.append('order_id', orderId);
    formData.append('new_status', status);
    
    return this.multipartRequest('/artisan/update-order-status', formData);
  }

  // Marketing Hub API
  async generateMarketingContent(imageFile: File, contentType: string, customPrompt?: string) {
    const formData = new FormData();
    formData.append('image', imageFile);
    formData.append('contentType', contentType);
    
    if (customPrompt) {
      formData.append('customPrompt', customPrompt);
    }
    
    return this.multipartRequest('/artisan/generate-content', formData);
  }

  // Translation API
  async translateText(text: string, targetLang: string = 'hi') {
    return this.request('/artisan/translate', {
      method: 'POST',
      body: JSON.stringify({ text, target: targetLang }),
    });
  }

  // Text-to-Speech API
  async textToSpeech(text: string, lang: string = 'en', speakingRate: number = 1.0) {
    return this.request('/artisan/tts', {
      method: 'POST',
      body: JSON.stringify({ text, lang, speakingRate }),
    });
  }

  // Speech-to-Text API
  async speechToText(audioFile: File) {
    const formData = new FormData();
    formData.append('audio', audioFile);
    
    return this.multipartRequest('/artisan/stt', formData);
  }

  // Craft Education Modules API
  async getCraftEducationModules() {
    return this.request('/craft-education/modules');
  }

  async getCraftEducationModule(moduleId: string) {
    return this.request(`/craft-education/modules/${moduleId}`);
  }

  // Wishlist API
  async getWishlistItems(userId: string) {
    return this.request(`/wishlist?user_id=${userId}`);
  }

  async addToWishlist(userId: string, productId: string) {
    return this.request('/wishlist', {
      method: 'POST',
      body: JSON.stringify({ user_id: userId, product_id: productId }),
    });
  }

  async removeFromWishlist(userId: string, productId: string) {
    return this.request('/wishlist', {
      method: 'DELETE',
      body: JSON.stringify({ user_id: userId, product_id: productId }),
    });
  }

  // Product Search and Discovery
  async searchProducts(query: string, filters: any = {}) {
    return this.request('/marketplace/products', {
      method: 'POST',
      body: JSON.stringify({ query, filters }),
    });
  }

  async getFeaturedProducts() {
    return this.request('/marketplace/featured');
  }

  // Customer Reviews API
  async getProductReviews(productId: string) {
    return this.request(`/reviews/product/${productId}`);
  }

  async submitProductReview(productId: string, reviewData: any) {
    return this.request('/reviews', {
      method: 'POST',
      body: JSON.stringify({ product_id: productId, ...reviewData }),
    });
  }

  async getArtisanReviews(artisanId: string) {
    return this.request(`/reviews/artisan/${artisanId}`);
  }

  // Session Management for AI Agent (used in CropRecommendation and other AI-powered features)
  async startSession(userId: string, language: string = 'en') {
    const formData = new FormData();
    formData.append('user_id', userId);
    formData.append('language', language);

    return this.multipartRequest('/agent/start-session', formData);
  }

  async executeTask(sessionId: string, taskType: string, userInput?: string, file?: File) {
    const formData = new FormData();
    formData.append('session_id', sessionId);
    formData.append('task_type', taskType);
    
    if (userInput) {
      formData.append('user_input', userInput);
    }
    
    if (file) {
      formData.append('file', file);
    }
    
    formData.append('language', 'en'); // Default language

    return this.multipartRequest('/agent/execute-task', formData);
  }

  // Additional agent functionality for navigation and task execution
  async continueTask(sessionId: string, userResponse: string, language: string = 'en') {
    const formData = new FormData();
    formData.append('session_id', sessionId);
    formData.append('user_response', userResponse);
    formData.append('language', language);

    return this.multipartRequest('/agent/continue-task', formData);
  }

  async getAgentStatus(sessionId: string) {
    return this.request(`/agent/session/${sessionId}`);
  }

  async generateWorkflow(systemPrompt: string, userPrompt: string, uiSchema: any) {
    const payload = {
      system_prompt: systemPrompt,
      user_prompt: userPrompt,
      ui_schema: uiSchema
    };

    return this.request('/agent/generate-workflow', {
      method: 'POST',
      body: JSON.stringify(payload),
    });
  }
}

export const apiService = new ApiService();